sudo: required
services:
  - docker

before_install:
  - docker build -t skygao/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run skygao/react-test npm test -- --coverage

after_success:
  - docker build -t coolgao/multi-client ./client
  - docker build -t coolgao/multi-nginx ./nginx
  - docker build -t coolgao/multi-server ./server
  - docker build -t coolgao/multi-worker ./worker
  # Login to the docker CLI
  - docker login -u "$DOCKER_USERNAME " -p "$DOCKER_PASSWORD" docker.io
  - docker push coolgao/multi-client
  - docker push coolgao/multi-nginx
  - docker push coolgao/multi-server
  - docker push coolgao/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-764476329573
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY