sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t skygao/react-test

script:
  - docker run skygao/react-test npm test -- --coverage

after_success:
  - docker build -t skygao/multi-client ./client
  - docker build -t skygao/multi-nginx ./nginx
  - docker build -t skygao/multi-server ./server
  - docker build -t skygao/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push skygao/multi-client
  - docker push skygao/multi-nginx
  - docker push skygao/multi-server
  - docker push skygao/multi-worker